### ISSUE TITLE
Add/Update New Institution is not working

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-help#34]
Add:
All required fields were entered into the application, and when the Add New institution button was selected, nothing happened. 

Update: 
Upon searching for an institution, when the results are displayed below and the Update button is selected, when fields are updated and the Update the institution button is selected, nothing happened.

**Comment by awolfe76** [comment]
I'll leave this open for now, but #32 should have the fix. We can check again after that is merged and deployed.

**Comment by keileyo** [comment]
we can go ahead and close this one, right?
