### ISSUE TITLE
Add year selector to HMDA Help UI

### ISSUE THREAD

**Issue by Kibrael** [cfpb/hmda-help#84]
HMDA Help needs to differentiate between 2018 and 2019 (and other years in the future).

This is to keep the HMDA Panel correct for a given collection and submission year.

**Comment by omnipresent07** [comment]
Frontend can use the updated API endpoints: https://github.com/cfpb/hmda-platform/blob/master/docs/v2/api/admin-api.md

- `activityYear` should not be defaulted to 2018
- `GET` and `PUT` endpoint for `/institutions/<lei>` is now changed to accept a year `/institutions/<lei>/year/<year>`

**Comment by Kibrael** [comment]
Please set the default update screen to 2019.
