### ISSUE TITLE
Restore "Would you like to add it" behavior to multiyear

### ISSUE THREAD

**Issue by wpears** [cfpb/hmda-help#90]
When switching to multiyear search, we lost the message that allows users to add an institution they searched for but that returned a 404.

To do that in a multiyear approach, could either:
  - have a note per year "That institution doesn't exist in 2019. Would you like to add it?"..."That institution doesn't exist in 2018. Would you like to add it?"
  - track all requests and on completion check to see if all 404'd, if so, present a message like "That institution has no data for any filing period. Would you like to add it?

**Comment by chynnakeys** [comment]
Example of what this looks like: 
![image](https://user-images.githubusercontent.com/41752348/70920012-c2a3b000-2019-11ea-912e-85d2103cff82.png)
