### ISSUE TITLE
Add an institution page does not have a year selector

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-help#94]
The page for adding a new institution does not have a year selector. It should have a year selector with 2018,2019 or additional years. Based on the value selected in the drop down, the `POST` request that happens when clicking `Add an institution` will have `activityYear` set as that year.

**Comment by meissadia** [comment]
I'm seeing an Activity Year drop down and associated logic to include the flag in the API calls.

<img width="732" alt="activity-year" src="https://user-images.githubusercontent.com/2592907/68512555-fc70e200-0235-11ea-915d-0169598554f0.png">

**Comment by omnipresent07** [comment]
Thanks!
